version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping_db
    ports:
      - '3306:3306'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'